version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install build dependencies
          command: |
            apk add --no-cache \
              bash \
              make \
              git
      - run:
          name: Pull Existing Images for Cache
          command: |
            docker pull utensils/darling
            docker pull utensils/darling:lite-builder
      - run:
          name: Build Docker Image
          command: |
            make cached-build
      - run:
          name: Build Lite version
          command: |
            make cached-build-lite
      - run:
          name: List Docker Images
          command: |
            docker images --filter "label=org.label-schema.vendor=Utensils" --filter "dangling=false"
      - run:
          name: Push Docker Images
          command: |
            echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            make push