version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install build dependencies
          command: |
            apk add --no-cache \
              bash \
              git \
              jq \
              make
      - run:
          name: Build images
          command: |
            make 
      - run:
          name: List Docker Images
          command: |
            make list
      - run:
          name: Push Docker Images
          command: |
            make push
            make push-readme