version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install build dependencies
          command: |
            apk add --no-cache \
              bash \
              curl \
              git \
              jq \
              make
      - run:
          name: Pull cache images
          command: |
            docker pull utensils/darling:builder || exit 0
      - run:
          name: Make And Push Build image for cache re-use
          command: |
            make builder
            make push-builder
      - run:
          name: Make Runtime Image
          command: |
            make
      - run:
          name: List Docker Images
          command: |
            make list
      - run:
          name: Push Docker Runtime Image
          command: |
            make push
            make push-readme
      - run:
          name: Update MicroBadger
          command: |
            make update-micro-badge